### ISSUE TITLE
Window in incorrect position when DPI scaling is used

### ISSUE THREAD

**Issue by jhon** [CaptainProton42/GodotHoloPlay#2]
When DPI scaling is used on the main monitor, the window position ends up in the incorrect place for the looking glass display.

**Reproduction Steps:**
1. Set main monitor display to 200% scale
2. Place the Looking Glass display to the right of the main display
2. Launch the GodotHoloPlayDemo in the Godot editor

**Expected Results:**
The HoloPlayVolume renders on the Looking Glass display

**Actual Results:**
The display window appears halfway across the main display

**Comment by CaptainProton42** [comment]
Should be fixed in 631ca1c.

To be honest, I find it very confusing how scaling works in GLFW (at least when extending the display on Windows) so I hope this catches everything properly. The scale callback also doesn't seem to work properly, so please try not to change your DPI scale too much while running the plugin 😄 

Thanks for the report!

**Comment by CaptainProton42** [comment]
Reopening this as now exported projects and projects/scenes run from within the editor have incorrect window placement/scale (see #3).

Current workaround is still to set display scale to 100 %.

**Comment by CaptainProton42** [comment]
I'll consider this fixed as enablding HiDPI support in the project settings is a stable workaround.

#10 might be related.
